[package]
name = "minigamemaker"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs = "0.9.0"
sdl3 = { version = "0", features = ["build-from-source-static"] }
oxidase = { git = "https://github.com/branchseer/oxidase", package = "oxidase" }
v8 = "137.2.0"
